version = 0.1

[default.deploy.parameters]
stack_name = "feedback-curso-stack"
resolve_s3 = true
s3_prefix = "feedback-curso-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "DemoEmail=\"thiagotbr49@gmail.com\""

[default.global.parameters]
region = "sa-east-1"
