version = 0.1

[default.deploy.parameters]
stack_name = "feedback-curso-stack"
resolve_s3 = true
s3_prefix = "feedback-curso-stack"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
